import {
  IsNotEmpty,
  IsString,
  MaxLength,
  MinLength,
  IsEmail,
  IsOptional,
  IsEnum,
} from 'class-validator';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { Match } from 'src/common/decorators/match.decorator';

import { Role } from 'src/common/enums/roles.enum';

export class RegisterUserDto {
  // IDs are auto-generated by the database, do not accept from client.

  @ApiProperty({
    description: 'Unique username (5-30 characters).',
    example: 'jdoe',
    minLength: 5,
    maxLength: 30,
  })
  @IsNotEmpty({ message: 'Username is required' })
  @IsString()
  @MinLength(5, { message: 'Username must be at least 5 characters long' })
  @MaxLength(30, { message: 'Username must not exceed 30 characters' })
  userName: string;

  @ApiProperty({
    description: 'First name.',
    example: 'John',
    minLength: 2,
    maxLength: 50,
  })
  @IsNotEmpty({ message: 'First name is required' })
  @IsString()
  @MinLength(2, { message: 'First name must be at least 2 characters long' })
  @MaxLength(50, { message: 'First name must not exceed 50 characters' })
  firstName: string;

  @ApiProperty({
    description: 'Last name.',
    example: 'Doe',
    minLength: 2,
    maxLength: 50,
  })
  @IsNotEmpty({ message: 'Last name is required' })
  @IsString()
  @MinLength(2, { message: 'Last name must be at least 2 characters long' })
  @MaxLength(50, { message: 'Last name must not exceed 50 characters' })
  lastName: string;

  @ApiProperty({
    description: 'User email address.',
    example: 'john.doe@example.com',
    maxLength: 50,
  })
  @IsNotEmpty({ message: 'Email is required' })
  @IsEmail({}, { message: 'Invalid email format' })
  @MaxLength(50, { message: 'Email must not exceed 50 characters' })
  email: string;

  @ApiProperty({
    description: 'Password (8-60 characters).',
    example: 'P@ssw0rd123',
    minLength: 8,
    maxLength: 60,
  })
  @IsNotEmpty({ message: 'Password is required' })
  @MinLength(8, { message: 'Password must be at least 8 characters long' })
  @MaxLength(60, { message: 'Password must not exceed 40 characters' })
  password: string;

  @ApiProperty({
    description: 'Must match the password field.',
    example: 'P@ssw0rd123',
  })
  @IsNotEmpty({ message: 'Confirm password is required' })
  @Match('password', { message: 'Passwords do not match' })
  confirmPassword: string;

  @ApiProperty({
    description: 'Telephone number (up to 10 digits).',
    example: '8015551234',
    maxLength: 10,
  })
  @IsNotEmpty({ message: 'Phone number is required' })
  @IsString()
  @MaxLength(10, { message: 'Telephone number must not exceed 10 digits' })
  telephone: string;

  @ApiPropertyOptional({
    description: 'User role. Defaults to standard user when omitted.',
    enum: Role,
  })
  @IsOptional()
  @IsEnum(Role, { message: 'Invalid role value' })
  role?: Role;
}
